In [1]:
import numpy

In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.18.5


# Q1)

In [7]:
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Q2)

In [26]:
arr1 = np.array([[1,2,3,4,5]])
arr2 = np.array([[6,7,8,9,10]])
print(arr1)
print(arr2)

[[1 2 3 4 5]]
[[ 6  7  8  9 10]]


In [29]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
np.sort(arr)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Q3)

In [15]:
arr = np.array( [[ 1, 2, 3],[ 4, 5, 6]] )
print(arr.ndim)
print(arr.size)

2
6


# Q4)

In [64]:
a = np.array([[1,2]])
b = np.array([[3,4]])
b = a[np.newaxis, :]
b.shape

(1, 1, 2)

In [65]:
 b = np.expand_dims(a, axis=1)
 b.shape

(1, 1, 2)

# Q5)

In [36]:
a = np.array([[1, 2],[3, 4]]) 
b = np.array([[5, 6],[7, 8]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [38]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Q6)

In [56]:
x = np.array([1,1,7,2,10,2,7,10,1,7,1])
unique,counts = np.unique(x,return_counts=True)
print(np.array((unique, counts)).T)

[[ 1  4]
 [ 2  2]
 [ 7  3]
 [10  2]]
